# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EX-TRA-T
email: extrat.bk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nous avons des compétences juridiques, administratives, logistiques et commerciales pour mieux vous servirez. Tout les moyens sont à nos porter pour que vos marchandises arrivent dans les délais et à bon port.
  Expérience Transit Transport a été crée depuis 20-- par son actuel gérant M. Kouma.
  Expérimenté dans le domaine du transit international et dans la gestion.
  Vous offre service flexible.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://transitdakar.ml" # the base hostname & protocol for your site
twitter_username: kkoumabassekou
github_username:  fadiga
facebook_username:  kouma.bassekou.9
# Build settings
phone_221: +221 77 055 36 27 / + 221 77 775 90 56
phone_223: +223 76 10 98 60